---
compact: true
directory:
  - .
skip-path:
  - tests
skip-check:
  - CKV_K8S_49 # Minimize wildcard use in Roles and ClusterRoles
  - CKV_K8S_155 # Minimize ClusterRoles that grant control over validating or mutating admission webhook configurations
  - CKV_K8S_156 # Minimize ClusterRoles that grant permissions to approve CertificateSigningRequests
  - CKV_K8S_157 # Minimize Roles and ClusterRoles that grant permissions to bind RoleBindings or ClusterRoleBindings
  - CKV_K8S_158 # Minimize Roles and ClusterRoles that grant permissions to escalate Roles or ClusterRoles
